#!/bin/bash
# build-project --- Build the project from sources.
export TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

set -e

cd $PROJ_DIR

if ! tslint --format=verbose src/*.ts src/test/*.ts; then
    LINT_ERROR=true
fi

echo -e "\nCompiling TypeScript files ..."
if ! tsc; then
    TSC_ERROR=true
fi
chmod +x lib/index.js

echo -e "\nPackaging ..."
npm pack 2>&1 | cat
mkdir -p dist
mv *.tgz dist
ls -l dist

if [[ "$LINT_ERROR" == "true" ]]; then
    echo -e "\n================================"
    echo "Fix lint errors!"
    echo -e "================================\n"
fi

if [[ "$TSC_ERROR" == "true" ]]; then
    echo -e "\n================================"
    echo "Fix TypeScript errors!"
    echo -e "================================\n"
fi
